// Package config loads and validates acme-agent's YAML configuration files
// for both binaries: the hub (cmd/acme-hub) and the spoke
// (cmd/acme-spoke).
package config

import (
	"fmt"
	"os"
	"regexp"
	"strings"
	"time"
	"unicode"

	"gopkg.in/yaml.v3"
)

// Duration wraps time.Duration so config fields can be written as plain
// strings in YAML (e.g. "1h", "30s") instead of raw nanosecond integers.
// It satisfies yaml.v3's Unmarshaler interface via UnmarshalYAML below.
type Duration time.Duration

// UnmarshalYAML implements yaml.Unmarshaler by parsing the YAML scalar as a
// Go duration string (anything time.ParseDuration accepts).
func (d *Duration) UnmarshalYAML(value *yaml.Node) error {
	var s string
	if err := value.Decode(&s); err != nil {
		return err
	}
	parsed, err := time.ParseDuration(s)
	if err != nil {
		return fmt.Errorf("invalid duration %q: %w", s, err)
	}
	// time.ParseDuration itself accepts negative strings (e.g. "-1h")
	// without complaint; nothing downstream (renewal-due comparisons,
	// ticker intervals, context.WithTimeout) expects one, and a negative
	// timeout in particular would fire immediately rather than never or
	// eventually. Every Duration field in both configs flows through this
	// one choke point, so rejecting it here covers all of them at once.
	if parsed < 0 {
		return fmt.Errorf("duration %q must not be negative", s)
	}
	*d = Duration(parsed)
	return nil
}

// Duration returns d as a standard time.Duration.
func (d Duration) Duration() time.Duration {
	return time.Duration(d)
}

// ACMEConfig selects the ACME CA and identity used for account registration.
type ACMEConfig struct {
	Environment string `yaml:"environment"` // "staging" or "production" - Let's Encrypt only; leave unset when DirectoryURL is set
	// Email is optional - RFC 8555's contact field isn't required to
	// register an account, and lego omits Contact entirely when this is
	// empty (see registration.registrar). Let's Encrypt no longer sends
	// expiration notices to it either way; the only remaining use is as a
	// CA-initiated security contact (e.g. mandatory revocation notices).
	Email string `yaml:"email"`

	// DirectoryURL points this project at any ACME-compliant CA's
	// directory endpoint - public or private - instead of Let's Encrypt.
	// Mutually exclusive with Environment: set exactly one. Left unset,
	// Environment's "staging"/"production" mapping to Let's Encrypt's own
	// two directory URLs is unchanged from before this field existed.
	DirectoryURL string `yaml:"directory_url"`

	// CACertFile trusts a private CA's own TLS certificate on its ACME API
	// endpoint - a different trust relationship than the certificates
	// this project requests from that CA. A public CA's API endpoint is
	// already covered by the OS trust store; a private CA's usually isn't.
	// Optional, and only meaningful alongside DirectoryURL.
	CACertFile string `yaml:"ca_cert_file"`

	// EAB (External Account Binding, RFC 8555 SS7.3.4) is required by some
	// CAs - both some private CA setups and some public ones (e.g. Google
	// Trust Services) - to gate account registration. Optional; both
	// fields must be set together or not at all. EABKeyID is the key
	// identifier; EABHMACKey is the base64url-encoded HMAC key, both
	// issued by the CA out of band (never generated by this project).
	EABKeyID   string `yaml:"eab_key_id"`
	EABHMACKey string `yaml:"eab_hmac_key"`
}

func (a ACMEConfig) validate() error {
	if a.Environment != "" && a.DirectoryURL != "" {
		return fmt.Errorf("acme.environment and acme.directory_url are mutually exclusive - set exactly one")
	}
	if a.DirectoryURL == "" && a.Environment != "staging" && a.Environment != "production" {
		return fmt.Errorf("acme.environment must be %q or %q, got %q", "staging", "production", a.Environment)
	}
	if (a.EABKeyID == "") != (a.EABHMACKey == "") {
		return fmt.Errorf("acme.eab_key_id and acme.eab_hmac_key must both be set, or neither")
	}
	return nil
}

// DNSProviderConfig configures one named DNS-01 credential set, held only by
// the hub (spokes never see DNS provider credentials — see
// internal/hubapi). Type selects the internal/dnsprovider factory
// implementation to use; which of the fields below apply depends on Type.
type DNSProviderConfig struct {
	Type string `yaml:"type"`

	// cloudflare
	APIToken string `yaml:"api_token"`

	// route53 (AWS). By default, credentials come from the standard AWS
	// SDK credential chain (environment variables, ~/.aws/credentials, or
	// an IAM role) rather than this file, per AWS's own guidance against
	// long-lived keys in application config — leave AccessKeyID/
	// SecretAccessKey/SessionToken unset to get that behavior, which is
	// the recommended default and the only option for a single-account
	// deployment.
	//
	// They exist as an explicit override for the case the SDK chain can't
	// cover: more than one route53_* entry needing genuinely different
	// AWS credentials (e.g. two separate AWS accounts' hosted zones
	// managed from one hub) — the SDK chain resolves exactly one set of
	// ambient credentials for the whole process, shared by every entry
	// that doesn't override it. lego's route53 provider only uses these
	// if both AccessKeyID and SecretAccessKey are set (SessionToken is
	// optional, only meaningful for temporary/STS-issued credentials, and
	// requires the other two to also be set).
	//
	// HostedZoneID and Region are optional overrides, independent of
	// credentials - they apply regardless of which credential source is
	// in effect for this entry.
	AccessKeyID     string `yaml:"access_key_id"`
	SecretAccessKey string `yaml:"secret_access_key"`
	SessionToken    string `yaml:"session_token"`
	HostedZoneID    string `yaml:"hosted_zone_id"`
	Region          string `yaml:"region"`

	// godaddy
	APIKey    string `yaml:"api_key"`
	APISecret string `yaml:"api_secret"`

	// pdns (self-hosted PowerDNS). APIURL is required (e.g.
	// "http://127.0.0.1:8081"); ServerName is optional and defaults to
	// "localhost", PowerDNS's own default virtual server ID.
	APIURL     string `yaml:"api_url"`
	ServerName string `yaml:"server_name"`

	// rfc2136 (TSIG-authenticated dynamic DNS updates - BIND, Windows AD
	// DNS, etc.). Nameserver is the authoritative server's host:port to
	// send UPDATE messages to (e.g. "127.0.0.1:53"). TSIGAlgorithm is
	// optional; lego defaults to HMAC-SHA1 if left blank - prefer setting
	// it explicitly (e.g. "hmac-sha256.") to match whatever algorithm the
	// TSIG key was actually generated with.
	Nameserver    string `yaml:"nameserver"`
	TSIGKey       string `yaml:"tsig_key"`
	TSIGSecret    string `yaml:"tsig_secret"`
	TSIGAlgorithm string `yaml:"tsig_algorithm"`
}

// EnvSource resolves one ${VAR} reference during config loading - see
// expandEnv. LoadSpokeConfig uses osEnvSource directly (the process's own
// environment; spokes are never hot-reloaded, so this is never a
// problem). LoadHubConfig uses fileEnvSource instead, reading an env file
// fresh on every call, since a long-running hub process's own
// environment is fixed at exec time and can never gain or update a
// variable afterward, no matter how many times it's asked to reload -
// see ARCHITECTURE.md "Config hot-reload".
type EnvSource func(name string) (string, bool)

func osEnvSource(name string) (string, bool) {
	return os.LookupEnv(name)
}

// loadYAML reads path, expands ${VAR} references via env, and unmarshals
// the result into a fresh T. Shared by LoadHubConfig and LoadSpokeConfig
// so secret-interpolation behavior (no secrets ever need to be written
// into the file itself) stays identical across both.
func loadYAML[T any](path string, env EnvSource) (*T, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config file: %w", err)
	}

	expanded, err := expandEnv(string(raw), env)
	if err != nil {
		return nil, err
	}

	var cfg T
	if err := yaml.Unmarshal([]byte(expanded), &cfg); err != nil {
		return nil, fmt.Errorf("parse config file: %w", err)
	}

	return &cfg, nil
}

// envVarPattern matches only the braced ${VAR} form. Deliberately not
// os.ExpandEnv (which also recognizes bare $VAR per Go stdlib semantics,
// with no way to disable that selectively): a bare "$" in a config value
// - a DNS provider secret, say - shouldn't silently trigger expansion just
// because it's followed by something that looks like an identifier.
var envVarPattern = regexp.MustCompile(`\$\{([A-Za-z_][A-Za-z0-9_]*)\}`)

// expandEnv replaces every ${VAR} in s with env's value for that name,
// leaving bare $VAR untouched. Unlike os.ExpandEnv, an unset variable is
// an error rather than a silent expansion to "" - a config that
// references ${CLOUDFLARE_API_TOKEN} but has a typo'd or forgotten env
// var should fail loudly at load time with that variable's name, not
// produce a mysteriously-empty api_token that only surfaces as a less
// specific validate() error (or, worse, no error at all, if the field it
// landed in happens to have no required-non-empty check).
//
// Lines that are entirely a YAML comment (first non-whitespace character
// is "#") are left untouched rather than scanned for ${VAR} - both
// example configs in deploy/ document optional fields exactly this way
// (e.g. "# eab_key_id: "${ACME_EAB_KEY_ID}""), and erroring on a
// deliberately-unset variable an operator has no intention of using yet,
// just because it appears inside its own commented-out documentation,
// would make that documentation pattern unusable under the stricter,
// error-on-unset behavior above.
func expandEnv(s string, env EnvSource) (string, error) {
	lines := strings.Split(s, "\n")

	var missing string
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}
		lines[i] = envVarPattern.ReplaceAllStringFunc(line, func(match string) string {
			name := envVarPattern.FindStringSubmatch(match)[1]
			if val, ok := env(name); ok {
				return val
			}
			if missing == "" {
				missing = name
			}
			return match
		})
	}
	if missing != "" {
		return "", fmt.Errorf("environment variable %q is referenced in the config but not set", missing)
	}
	return strings.Join(lines, "\n"), nil
}

// fileEnvSource returns an EnvSource that reads envFilePath fresh on
// every call, falling back to the process's own environment for any name
// not found in the file - the mechanism that makes LoadHubConfig
// actually able to see a variable added to the file after the process
// started (see EnvSource's doc comment for why the process's own
// environment alone can't).
//
// If envFilePath doesn't exist, or can't be read due to a permissions
// problem, this falls back to exactly osEnvSource rather than erroring -
// not every deployment necessarily uses a separate env file (secrets
// could be injected some other way, e.g. systemd Environment= lines
// directly in the unit), and treating a permission error as fatal would
// mean a misconfigured file-access grant (see ARCHITECTURE.md "Config
// hot-reload" on the DynamicUser/SupplementaryGroups setup this depends
// on in production) breaks the hub outright instead of degrading to
// exactly today's behavior: reload keeps working, it just can't see
// variables added to the file since the process started, the same
// limitation that existed before this mechanism at all.
func fileEnvSource(envFilePath string) (EnvSource, error) {
	vars, err := parseEnvFile(envFilePath)
	if err != nil {
		if os.IsNotExist(err) || os.IsPermission(err) {
			return osEnvSource, nil
		}
		return nil, fmt.Errorf("read env file %s: %w", envFilePath, err)
	}
	return func(name string) (string, bool) {
		if v, ok := vars[name]; ok {
			return v, true
		}
		return os.LookupEnv(name)
	}, nil
}

// parseEnvFile reads simple KEY=VALUE lines (blank lines and lines whose
// first non-whitespace character is "#" ignored) - the same shape a
// systemd EnvironmentFile= uses, since this is meant to read the exact
// file that directive already points at (see deploy/acme-hub.service).
// Not a general-purpose env file parser: no quoting, no export keyword,
// no variable expansion within the file itself - acme-hub.env's own
// values (bearer tokens, DNS provider credentials) never need any of
// that.
func parseEnvFile(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	vars := make(map[string]string)
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		name, value, ok := strings.Cut(trimmed, "=")
		if !ok {
			return nil, fmt.Errorf("invalid line (expected KEY=VALUE): %q", trimmed)
		}
		vars[strings.TrimSpace(name)] = value
	}
	return vars, nil
}

// validateDomain rejects obviously malformed domain strings - not a full
// hostname validator (deliberately loose, so it can't false-reject a
// legitimate but unusual hostname), just enough to catch the operator
// typos an empty-slice check alone can't: a blank string sitting in the
// domains list, or stray whitespace from a copy-paste. A single leading
// "*." is explicitly allowed, since wildcard certificates are a normal,
// already-tested case.
func validateDomain(d string) error {
	if d == "" {
		return fmt.Errorf("domain must not be empty")
	}
	for _, r := range d {
		if unicode.IsSpace(r) || unicode.IsControl(r) {
			return fmt.Errorf("domain %q contains whitespace or control characters", d)
		}
	}
	if strings.TrimPrefix(d, "*.") == "" {
		return fmt.Errorf("domain %q has no hostname after the wildcard", d)
	}
	return nil
}

// validateCertName rejects a certificate name that isn't safe to use as a
// single path component. Both configs' cert names end up in a filesystem
// path unguarded (internal/spokeagent.ProcessCert does
// filepath.Join(dataDir, "certs", cert.Name)), so a name like "../../etc"
// or containing a "/" would otherwise pass validation and let certwriter
// write outside the intended certs directory.
func validateCertName(name string) error {
	if name == "" {
		return fmt.Errorf("name is required")
	}
	if name == "." || name == ".." || strings.ContainsAny(name, `/\`) {
		return fmt.Errorf("cert name %q must be a single path component - no \"/\", and not \".\" or \"..\"", name)
	}
	return nil
}
